dist: xenial
language: python

addons:
  apt:
    packages:
    - netcdf-bin

install:
  - pip install scipy netcdf4

python:
  - "2.7"
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"

script:
  - make
  - make check
