dist: xenial
language: python

install:
  - pip install scipy

python:
  - "2.7"
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"

script:
  - python test.py
  - ncdump test1.nc > test1.cdf
  - ncdump test1.nc > test2.cdf
  - git diff
  - md5sum *.nc
  - md5sum -c test.md5
